version: "2.2"
services:
  # --BACK--
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: nadir92/devoir_image:latest
    container_name: back
    ports:
      - 3000:3000
    networks:
      - elk

  # --FRONT--
  front:
    build:
      context: ./front
    container_name: front
    ports:
      - 3001:3001
    networks:
      - elk

networks:
  elk:
    driver: bridge
