apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nadir
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-nadir
  template:
    metadata:
      labels:
        app: backend-nadir
    spec:
      containers:
        - name: backend-nadir
          image: nadir92/devoir_image_back:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nadir-service
spec:
  selector:
    app: backend-nadir
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
