apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nadir
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-nadir
  template:
    metadata:
      labels:
        app: frontend-nadir
    spec:
      containers:
        - name: frontend-nadir
          image: nadir92/devoir_image_front:latest
          ports:
            - containerPort: 3214
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nadir-service
spec:
  selector:
    app: frontend-nadir
  ports:
    - protocol: TCP
      port: 3214
      targetPort: 3214
  type: LoadBalancer
