name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t nadir92/devoir_image:latest .
          docker push nadir92/devoir_image:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion Azure
        run: |
          az login -u "${{ secrets.APP_ID }}" --service-principal -p "${{ secrets.AZURE_PWD }}" --tenant "${{ secrets.TENANT_ID }}"
          az aks get-credentials --resource-group hitema_kube --name hitema

      - name: Deploy backend
        run: |
          echo "Current Path: $GITHUB_WORKSPACE"
          kubectl apply -f back/backend.yml
