name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image BACK
        run: |
          docker build -t nadir92/devoir_image_back:latest ./back
          docker push nadir92/devoir_image_back:latest
      - name: Build and Push Docker Image FRONT
        run: |
          docker build -t nadir92/devoir_image_front:latest ./front
          docker push nadir92/devoir_image_front:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Connexion Azure
        run: |
          az login -u "${{ secrets.APP_ID }}" --service-principal -p "${{ secrets.AZURE_PWD }}" --tenant "${{ secrets.TENANT_ID }}"
          az aks get-credentials --resource-group hitema_kube --name hitema

      - name: Clear cache
        run: 
      - name: Deploy backend
        run: kubectl apply -f back/backend.yml
      - name: Deploy frontend
        run: kubectl apply -f front/frontend.yml
