name: Deploy AKS Cluster

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t nadir92/devoir_image:latest ./back
          docker push nadir92/devoir_image:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubernetes CLI
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Connexion Azure
        run: az login -u "${{APP_ID}}" --service-principal -p "${{AZURE_PWD}}" --tenant "${{TENANT_ID}}"
